"""NL to Cedar Compiler module."""

import hashlib
import logging
from decimal import Decimal
from typing import Any

from pydantic import BaseModel, Field

from agentiam_controlplane.nl_compiler.llm import LLMClient, client_from_env
from agentiam_core.policy_testing import PolicyTestCase

logger = logging.getLogger(__name__)

#: A statement is user-authored English that may name individuals or amounts. Logging it
#: verbatim leaks whatever the operator typed into their console (`ENGINEERING-RULES`
#: rule 10, `PLAN.md` NFR-5). The digest is a correlation handle across the compile
#: request, its evaluation, and the audit record — same shape as spec 10 §5.4's
#: ``arg_digest`` for the same reason.
_STATEMENT_DIGEST_BYTES = 8


def _statement_digest(statement: str) -> str:
    """A short, stable handle for a natural-language statement, suitable for logs."""
    return hashlib.sha256(statement.encode("utf-8")).hexdigest()[: _STATEMENT_DIGEST_BYTES * 2]


class CompilerTestCase(BaseModel):
    """A test case generated by the compiler to verify its own policy output.

    The fields mirror `agentiam_core.policy_testing.PolicyTestCase`, so a generated test
    is evaluated through exactly the same path as the 51-case corpus and the activation
    gate. The previous shape named a principal id and a resource type, which could only
    be checked against an empty entity list — so those tests turned on guessing ids
    rather than on the policy being right (STATUS gap 19).
    """

    name: str = Field(..., description="A short, descriptive name for the test.")
    description: str = Field(..., description="What the test is asserting.")
    expected: bool = Field(
        ..., description="True if the request should be allowed, False if denied."
    )
    role: str = Field(default="worker", description="The agent's role, e.g. 'worker' or 'senior'.")
    operation: str = Field(..., description="The scope attempted, e.g. 'invoice:read'.")
    tool: str = Field(
        default="invoice_api",
        description="One of invoice_api, vendor_api, payment_api, email_internal, email_external.",
    )
    amount: str = Field(default="0", description="Payment amount as a decimal string, e.g. '5000'.")
    depth: int = Field(default=1, description="The agent's delegation depth, 1 for a root agent.")
    elevated: bool = Field(default=False, description="Whether an approver elevated the request.")
    environment: str = Field(default="production", description="Usually 'production'.")

    def as_policy_test_case(self) -> PolicyTestCase:
        """The core `PolicyTestCase` this describes, for the shared evaluator."""
        return PolicyTestCase(
            name=self.name,
            description=self.description,
            operation=self.operation,
            expected=self.expected,
            role=self.role,
            tool=self.tool,
            amount=Decimal(self.amount or "0"),
            depth=self.depth,
            elevated=self.elevated,
            environment=self.environment,
        )


class CompilerOutput(BaseModel):
    """The structured output from the NL->Policy compiler."""

    clarifying_question: str | None = Field(
        default=None,
        description="Ask a question if input is ambiguous. Only set if you cannot guess.",
    )
    cedar_source: str | None = Field(
        default=None,
        description="The compiled Cedar policy source code. Omit if asking a clarifying question.",
    )
    tests: list[CompilerTestCase] = Field(
        default_factory=list,
        description="Test cases to verify the policy. Omit if ambiguous. Must include Allow/Deny.",
    )


_SYSTEM_PROMPT = """You are a Cedar policy compiler for AgentIAM. Translate the requirement
into a Cedar policy over the fixed schema below, and generate test cases for it.

THE SCHEMA IS FIXED. Never invent entity types.

  principal  Agent   attributes: role (string), depth (number)
  resource   Tool    attributes: sensitivity ("low"|"medium"|"critical"),
                                 is_external (boolean), server (string)
  action     the scope string, e.g. Action::"invoice:read"
  context            amount (decimal), elevated (boolean), environment (string)

Known tools: invoice_api, vendor_api, payment_api, email_internal, email_external.
Common roles: worker, senior, auditor. Common scopes: invoice:read, invoice:write,
vendor:read, payment:initiate, email:send.

WRITE POLICIES ABOUT ROLES, NOT INDIVIDUALS. "Managers can approve expenses" is
principal.role == "manager", never a named agent id.

SYNTAX RULES — these are the exact mistakes measured on earlier runs. Read them twice.

1. **Cedar uses `&&` and `||`. It has no `and` / `or` keywords.** Writing `and` is a
   parse error and was the single largest cause of failure.
   Wrong: when { principal.role == "senior" and context.amount.lessThan(decimal("10.0")) };
   Right: when { principal.role == "senior" && context.amount.lessThan(decimal("10.0")) };
2. **Only `context.amount` is a decimal.** Compare it with decimal methods. Everything
   else — including `principal.depth` — is an ordinary number compared with < <= > >= ==.
   Wrong: principal.depth.lessThan(3)
   Right: principal.depth < 3
3. Leave a scope element unconstrained by writing it bare. Use `resource`, NEVER
   `resource == Resource::*` or `resource in Tool::*`. There is no `::*` in Cedar.
4. Every condition goes in a `when { }` clause after the scope, never inside the scope.
   Wrong: permit(principal, action, resource == Tool::"x" && x.sensitivity == "low");
   Right: permit(principal, action, resource) when { resource.sensitivity == "low" };
5. Money comparisons:
   context.amount.lessThanOrEqual(decimal("500000.0"))   for "at most" / "up to"
   context.amount.lessThan(decimal("10000.0"))           for "below" / "under"
6. Several actions: action in [Action::"invoice:read", Action::"vendor:read"].
7. **A `forbid` alone denies everything, because nothing permits.** "No agent may use an
   external tool" still needs a permit for what remains allowed:
   permit(principal, action, resource);
   forbid(principal, action, resource) when { resource.is_external };
8. Negate booleans with `!`, as in `!resource.is_external`.
9. Every policy ends with a semicolon.
10. Two different rules are two separate policies, not one policy with `||`. "Seniors up
    to 1000000, everyone else up to 1000" is two permits.

WHEN TO ASK INSTEAD OF COMPILING:
Ask a `clarifying_question` ONLY if the requirement names no actor at all, or no action at
all, or contradicts itself. Do NOT ask merely because a role or resource is generic —
"agents", "any agent", "senior agents" are all perfectly clear. If you can identify who and
what, COMPILE IT.

EXAMPLES

Requirement: Auditor agents may send email.
permit(principal, action == Action::"email:send", resource)
when { principal.role == "auditor" };

Requirement: Agents may initiate payments of at most 7500.
permit(principal, action == Action::"payment:initiate", resource)
when { context.amount.lessThanOrEqual(decimal("7500.0")) };

Requirement: Agents may read vendor records, but never on a critical tool.
permit(principal, action == Action::"vendor:read", resource);
forbid(principal, action, resource) when { resource.sensitivity == "critical" };

Requirement: Auditor agents may read vendor records at depth 4 or shallower.
permit(principal, action == Action::"vendor:read", resource)
when { principal.role == "auditor" && principal.depth <= 4 };

Requirement: Senior agents may send email anywhere; everyone else only internally.
permit(principal, action == Action::"email:send", resource)
when { principal.role == "senior" };
permit(principal, action == Action::"email:send", resource)
when { principal.role != "senior" && !resource.is_external };

Put the policy in `cedar_source` and give `tests` covering both an allowed case
(expected=true) and a denied case (expected=false).
"""


async def compile_nl_to_policy(
    nl_statement: str, client: LLMClient | None = None
) -> CompilerOutput:
    """Compile a natural language statement into a Cedar policy and auto-generate tests.

    Args:
        nl_statement: The English description of the policy.
        client: An optional backend. Defaults to whichever `AGENTIAM_LLM_BACKEND` selects
            — Groq while this is a prototype, Ollama in production (ADR-040).

    Returns:
        CompilerOutput containing the Cedar source and the generated tests.
    """
    if client is None:
        client = client_from_env()

    prompt = f"{_SYSTEM_PROMPT}\n\nREQUIREMENT:\n{nl_statement}\n"
    schema: dict[str, Any] = CompilerOutput.model_json_schema()

    logger.info(
        "compiling NL statement (sha256[:16]=%s, length=%d)",
        _statement_digest(nl_statement),
        len(nl_statement),
    )
    raw_output = await client.generate_structured(prompt=prompt, schema=schema)

    return CompilerOutput.model_validate(raw_output)
