"""NL to Cedar Compiler module."""

import logging
from typing import Any

from pydantic import BaseModel, Field

from agentiam_controlplane.nl_compiler.ollama_client import OllamaClient

logger = logging.getLogger(__name__)


class CompilerTestCase(BaseModel):
    """A test case generated by the compiler to verify its own policy output."""

    name: str = Field(..., description="A short, descriptive name for the test.")
    description: str = Field(..., description="What the test is asserting.")
    expected: bool = Field(
        ..., description="True if the request should be allowed, False if denied."
    )
    principal_id: str = Field(
        ..., description="The ID of the principal (e.g., 'worker1', 'admin')."
    )
    action: str = Field(..., description="The action being attempted (e.g., 'invoice:read').")
    resource_type: str = Field(..., description="The type of the resource (e.g., 'Invoice').")
    resource_id: str = Field(..., description="The ID of the resource (e.g., 'inv-123').")


class CompilerOutput(BaseModel):
    """The structured output from the NL->Policy compiler."""

    clarifying_question: str | None = Field(
        default=None,
        description="Ask a question if input is ambiguous. Only set if you cannot guess.",
    )
    cedar_source: str | None = Field(
        default=None,
        description="The compiled Cedar policy source code. Omit if asking a clarifying question.",
    )
    tests: list[CompilerTestCase] = Field(
        default_factory=list,
        description="Test cases to verify the policy. Omit if ambiguous. Must include Allow/Deny.",
    )


_SYSTEM_PROMPT = """You are an expert IAM policy compiler.
Translate the natural language requirement into a valid Cedar policy and generate test cases.

CRITICAL RULES FOR AMBIGUITY:
If the input is deliberately ambiguous or lacks context (e.g. missing who, what, or which resource),
DO NOT guess. Instead, provide a `clarifying_question` asking for the missing context, and omit
`cedar_source` and `tests`.

CEDAR SYNTAX RULES:
1. Every policy must be either `permit` or `forbid`.
2. The scope must define `principal`, `action`, and `resource`.
3. Use exact string matching or `in` for hierarchies.
4. Example:
permit (
    principal == User::"alice",
    action == Action::"view",
    resource == Photo::"Vacation"
);

If there is no ambiguity, generate the policy in `cedar_source`, and provide `tests` to verify it.
Ensure there are tests for both positive (expected=true) and negative (expected=false) cases.
"""


async def compile_nl_to_policy(
    nl_statement: str, client: OllamaClient | None = None
) -> CompilerOutput:
    """Compile a natural language statement into a Cedar policy and auto-generate tests.

    Args:
        nl_statement: The English description of the policy.
        client: An optional OllamaClient. If not provided, a default one is instantiated.

    Returns:
        CompilerOutput containing the Cedar source and the generated tests.
    """
    if client is None:
        client = OllamaClient()

    prompt = f"{_SYSTEM_PROMPT}\n\nREQUIREMENT:\n{nl_statement}\n"
    schema: dict[str, Any] = CompilerOutput.model_json_schema()

    logger.info("Compiling NL statement to Cedar: %s", nl_statement)
    raw_output = await client.generate_structured(prompt=prompt, schema=schema)

    return CompilerOutput.model_validate(raw_output)
