"""`RESERVE`, `COMMIT` — spec 04 §4.2, §4.3, T-014.

PEP-side, local, and pure: no network, no ledger mutation, no lock (spec 04 §6's safety
table lists their effect on `Φ = committed + leased` as "none"). This is the hot path —
NFR-1 exists because a network round trip here would put one in the tool-call critical path.
`LocalLease.remaining_local` is the PEP's own cached view of what it can still spend; it is
never authoritative, and losing it costs the PEP its ability to spend, never the ledger's
accounting (spec 04 §2.3).

`LEDGER_COMMIT`, the one operation of the seven that does touch the database, is
`agentiam_controlplane.db.ledger.ledger_commit` — a genuinely separate module, since it needs
`AsyncSession` and this one must not.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from datetime import datetime, timedelta
from decimal import Decimal

from agentiam_core.models import LeaseState
from agentiam_pep.errors import ReservationInsufficientError


@dataclass
class LocalLease:
    """A PEP's in-memory view of one held lease — spec 04 §2.2, §2.3.

    `granted` and `expires_at` are the ledger-issued, immutable facts from `ACQUIRE`.
    `remaining_local` is mutated by `reserve()`/`commit()` and is the only field this module
    ever writes; `state` is refreshed by whatever polls or receives the revocation gossip
    (T-038), not by anything here.
    """

    id: uuid.UUID
    granted: Decimal
    remaining_local: Decimal
    expires_at: datetime
    state: LeaseState


@dataclass(frozen=True)
class Reservation:
    """A held slice of `LocalLease.remaining_local` — spec 04 §4.2.

    `id` is generated by the PEP, not the ledger, and is the idempotency key `LEDGER_COMMIT`
    dedups on (spec 04 §10) — it must survive unchanged from `RESERVE` through `COMMIT` to
    whatever eventually calls `ledger_commit()`.
    """

    id: uuid.UUID
    lease_id: uuid.UUID
    amount: Decimal


@dataclass(frozen=True)
class CommitOutcome:
    """What `commit()` produces for the caller to enqueue as `LEDGER_COMMIT` — spec 04 §4.3.

    `amount` is always the real, reported `actual` — never clamped or withheld here. The
    money was already spent (the tool call already happened) by the time `commit()` runs;
    `ledger_commit()`'s own G2 clamp, not this function, is what protects the pool from an
    over-reported `actual` (spec 04 §6: "a PEP cannot break this").
    """

    reservation_id: uuid.UUID
    lease_id: uuid.UUID
    amount: Decimal
    escalated: bool


def reserve(
    lease: LocalLease,
    amount: Decimal,
    *,
    now: datetime,
    skew: timedelta,
    reservation_id: uuid.UUID | None = None,
) -> Reservation:
    """`RESERVE` — spec 04 §4.2.

    Mutates `lease.remaining_local` on success; leaves it untouched on any failure.

    Raises:
        ReservationInsufficientError: the lease is not `active`, `now` is at or past
            `expires_at - skew` (expire early, spec 04 §9), or `remaining_local < amount`.
    """
    if amount < 0:
        raise ValueError("amount must be non-negative")
    if lease.state != LeaseState.ACTIVE:
        raise ReservationInsufficientError(f"lease {lease.id} is not active")
    if now >= lease.expires_at - skew:
        raise ReservationInsufficientError(f"lease {lease.id} is within the skew margin")
    if lease.remaining_local < amount:
        raise ReservationInsufficientError(
            f"lease {lease.id} has {lease.remaining_local} remaining, {amount} requested"
        )
    lease.remaining_local -= amount
    return Reservation(id=reservation_id or uuid.uuid4(), lease_id=lease.id, amount=amount)


def commit(
    lease: LocalLease,
    reservation: Reservation,
    actual: Decimal,
    *,
    now: datetime,
    skew: timedelta,
) -> CommitOutcome:
    """`COMMIT` — spec 04 §4.3. `actual` may differ from `reservation.amount` either way.

    An over-estimate (`actual < reservation.amount`) refunds the exact difference to
    `remaining_local`. An under-estimate (`actual > reservation.amount`) attempts to cover
    the shortfall from `remaining_local` via `reserve()`; if that fails, `escalated=True` on
    the returned outcome rather than raising — the spend already happened and must still be
    reported to `LEDGER_COMMIT`, escalation is a signal for the caller, not a reason to drop it.
    """
    delta = actual - reservation.amount
    escalated = False
    if delta > 0:
        try:
            reserve(lease, delta, now=now, skew=skew)
        except ReservationInsufficientError:
            escalated = True
    elif delta < 0:
        lease.remaining_local += -delta
    return CommitOutcome(
        reservation_id=reservation.id, lease_id=lease.id, amount=actual, escalated=escalated
    )


__all__ = ["CommitOutcome", "LocalLease", "Reservation", "commit", "reserve"]
